type QuestionFormProps = {
  topic: string
  prompt: string
  isSubmitting: boolean
  error: string | null
  onTopicChange: (value: string) => void
  onPromptChange: (value: string) => void
  onSubmit: () => void
}

function QuestionForm({
  topic,
  prompt,
  isSubmitting,
  error,
  onTopicChange,
  onPromptChange,
  onSubmit,
}: QuestionFormProps) {
  return (
    <article className="panel form-panel">
      <div className="panel-header">
        <div>
          <p className="section-label">Input</p>
          <h2>New question</h2>
        </div>
      </div>

      <label className="field-label" htmlFor="topic">
        Topic
      </label>
      <input
        id="topic"
        className="text-input"
        value={topic}
        onChange={(event) => onTopicChange(event.target.value)}
        placeholder="general"
      />

      <label className="field-label" htmlFor="question">
        Prompt
      </label>
      <textarea
        id="question"
        className="text-area"
        rows={8}
        value={prompt}
        onChange={(event) => onPromptChange(event.target.value)}
        placeholder="Ask a question about your documents or workflow."
      />

      <div className="form-footer">
        <button
          type="button"
          className="primary-button"
          onClick={onSubmit}
          disabled={isSubmitting}
        >
          {isSubmitting ? 'Sending...' : 'Send question'}
        </button>
        <p className="helper-text">Responses are generated by the configured model.</p>
      </div>

      {error ? <p className="error-text">{error}</p> : null}
    </article>
  )
}

export default QuestionForm
